apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 3  # Nombre de répliques (ajustez selon vos besoins)
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: python:3.10-slim
        ports:
        - containerPort: 5000 # Port sur lequel l'application écoute
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Port du conteneur
  type: LoadBalancer # Type de service pour accéder à l'application depuis l'extérieur
